oeApp.config(['$translateProvider', function ($translateProvider) {
  $translateProvider.translations('en', {
    'HOME': 'Home',
    'PORTALS': 'Portals',
    'SELECT_EN': 'Filter Websites in English',
    'SELECT_FR': 'Filter Websites in French',
    'MOVE_BLOCS': 'Move blocs',
    'ABOUT': 'ABOUT',
    'BY': 'by',
    'VIEWERS': 'viewers',
    'WITH': 'with',
    'INFO_TITLE': 'About Open eSport',
    'INFO_DESCRIPTION': 'Make your custom feed by picking your favorite websites and enjoy the best eSport articles in French and in English !',
    'ANDROID_TITLE': 'Also available on Android',
    'ANDROID_DESCRIPTION': 'You can find Open eSport and all of its features at the ',
    'THANKS': 'Thanks',
    'THANKS_DESCRIPTION': 'Thanks to Stephane \'deKey\' Sanchez for the logo and to Edouard \'xiN\' Forgeau for his feedbacks.\n\nOpen eSport is a part of Nodejitsu Open Source program.',
  	'CONTACT_DESCRIPTION': 'You can find all the latest updates with the twitter account: ',
  	'CONTACT_DESCRIPTION2': 'Contact Open eSport by email at esportopen[at]gmail[dot]com.',
    'NO_ARTICLE': 'No article.',
    'MORE': 'More',
    'FILTER': 'Filters',
    'ARTICLES_TITLE': 'All The News',
    'STREAMS': 'Streams',
  });
 
  $translateProvider.translations('fr', {
    'HOME': 'Accueil',
    'PORTALS': 'Portails',
    'SELECT_EN': 'Filtrer les Sites anglophones',
    'SELECT_FR': 'Filtrer les Sites francophones',
    'MOVE_BLOCS': 'Déplacer les blocs',
    'ABOUT': 'À PROPOS',
    'BY': 'par',
    'VIEWERS': 'spectateurs',
    'WITH': 'avec',
    'INFO_TITLE': 'Open eSport ?',
    'INFO_DESCRIPTION': 'Créez votre flux d\'articles en choisissant vos jeux et vos sites favoris puis profitez de toute l\'actualité eSport sur une unique page.\n\nOpen eSport rassemble les articles des meilleures rédactions francophones et anglophones.',
    'ANDROID_TITLE': 'Aussi disponible sur Android',
    'ANDROID_DESCRIPTION': 'Vous pouvez trouver Open eSport et toutes ses fonctionnalités sur le ',
    'THANKS': 'Remerciements',
    'THANKS_DESCRIPTION': 'Merci à Stephane \'deKey\' Sanchez pour le logo et à Edouard \'xiN\' Forgeau pour ses retours.\n\nOpen eSport fait partie du programme open source de nodejitsu.',
  	'CONTACT_DESCRIPTION': 'Retrouvez les dernières mises à jour du site sur twitter : ',
  	'CONTACT_DESCRIPTION2': 'Contactez Open eSport par mail à esportopen[arobase]gmail[point]com.',
  	'NO_ARTICLE': 'Aucun article disponible.',
    'MORE': 'Plus',
    'FILTER': 'Filtres',
    'ARTICLES_TITLE': 'Toute l\'Actualité',
  });
 
  $translateProvider.preferredLanguage('en');
}]);